# -*- coding: utf-8 -*-
"""Nutrition_Mining.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1zPFVNPRoF49yJfqUWZnjZBS7IP08vadE

Name: Sahana Nagaraj Reddy

Startup name : ZIVA

Endpoint: Nutrition

Group 2

JSON file link

https://www.kaggle.com/datasets/hugodarwood/epirecipes?resource=download&select=full_format_recipes.json
"""

import json
import os
import numpy as np
import matplotlib.pyplot as plt

# Load the JSON file
file_path = "C:/Users/SAHANA/PycharmProjects/DataWrangling/full_format_recipes.json"

with open(file_path, 'r') as file:
    recipes_data = json.load(file)

# Display the first few items to understand the structure of the data
recipes_data[:2]

# Analyzing the dataset for insights

# Initialize dictionaries to count categories, ingredients, and to accumulate ratings and nutritional info
categories_count = {}
ingredients_count = {}
ratings_sum = 0
ratings_count = 0
nutritional_info = {'fat': 0, 'calories': 0, 'protein': 0, 'sodium': 0}
nutritional_count = {'fat': 0, 'calories': 0, 'protein': 0, 'sodium': 0}

# Iterate through each recipe to populate the dictionaries and calculate sums
for recipe in recipes_data:
    # Categories
    for category in recipe.get('categories', []):
        categories_count[category] = categories_count.get(category, 0) + 1
    # Ingredients
    for ingredient in recipe.get('ingredients', []):
        ingredients_count[ingredient] = ingredients_count.get(ingredient, 0) + 1
    # Ratings
    if recipe.get('rating') is not None:
        ratings_sum += recipe['rating']
        ratings_count += 1
    # Nutritional information
    for key in nutritional_info.keys():
        if recipe.get(key) is not None:
            nutritional_info[key] += recipe[key]
            nutritional_count[key] += 1

# Calculate averages
average_rating = ratings_sum / ratings_count if ratings_count else 0
average_nutritional_info = {key: nutritional_info[key] / nutritional_count[key] if nutritional_count[key] else 0 for key in nutritional_info}

# Most common categories and ingredients
most_common_categories = sorted(categories_count.items(), key=lambda item: item[1], reverse=True)[:5]
most_common_ingredients = sorted(ingredients_count.items(), key=lambda item: item[1], reverse=True)[:5]

average_rating, average_nutritional_info, most_common_categories, most_common_ingredients

# Average Rating
print(f"Average Rating: {average_rating:.2f} out of 5")

# Average Nutritional Information
print("\nAverage Nutritional Information per Recipe:")
for nutrient, value in average_nutritional_info.items():
    print(f"- {nutrient.capitalize()}: {value:.2f}")

# Most Common Categories
print("\nMost Common Categories:")
for category, count in most_common_categories:
    print(f"- {category}: {count} recipes")

# Most Common Ingredients
print("\nMost Common Ingredients:")
for ingredient, count in most_common_ingredients:
    print(f"- {ingredient}: used in {count} recipes")

# Sorting in descending order
sorted_data = sorted(
    (d for d in recipes_data if d.get('title') and d.get('rating')),
    key=lambda x: x['rating'],
    reverse=True
)

# Print the top 5 recipes based on rating
for recipe in sorted_data[:5]:
    print(json.dumps({"title": recipe["title"], "rating": recipe["rating"]}, indent=4))

# Sorting in Ascending order
sorted_data = sorted(
    (d for d in recipes_data if d.get('title') and d.get('rating')),
    key=lambda x: x['rating']
)

# Print the least 5 recipes based on rating
for recipe in sorted_data[:5]:
    print(json.dumps({"title": recipe["title"], "rating": recipe["rating"]}, indent=4))

# Sorting the data of title and calories
sorted_data = sorted(
    (d for d in recipes_data if d.get('title') and d.get('calories')),
    key=lambda x: x['calories'],

)

# Print the top 5 recipes based on rating
for recipe in sorted_data[:5]:
    print(json.dumps({"title": recipe["title"], "calories": recipe["calories"]}, indent=4))

"""###The following visual insights into the most popular categories and ingredients in the recipes dataset are offered by the plots:

Top Categories:
**bold text**
This figure displays the categories in the dataset that appear most frequently. "Bon Appétit" is the most common category, followed by dietary preferences like "Peanut Free" and "Soy Free." This suggests that there is a good representation of recipes that satisfy particular dietary requirements and tastes.


Most Common Ingredients: **bold text**

The plot focuses on the ingredients that are most commonly used, with different proportions of salt and olive oil taking center stage. This emphasizes how essential these items are to cooking because they provide the flavoring for a lot of recipes.
"""

# Extracting data for plotting
categories_names = [cat[0] for cat in most_common_categories]
categories_counts = [cat[1] for cat in most_common_categories]

ingredients_names = [ing[0] for ing in most_common_ingredients]
ingredients_counts = [ing[1] for ing in most_common_ingredients]

# Create plots
fig, ax = plt.subplots(2, 1, figsize=(10, 12))

# Plot for most common categories
ax[0].barh(categories_names, categories_counts, color='skyblue')
ax[0].set_title('Most Common Categories')
ax[0].set_xlabel('Count')
ax[0].set_ylabel('Category')
plt.tight_layout()
plt.savefig('C:/Users/SAHANA/PycharmProjects/DataWrangling/Static/most_common_categories.png')

# Plot for most common ingredients
ax[1].barh(ingredients_names, ingredients_counts, color='lightgreen')
ax[1].set_title('Most Common Ingredients')
ax[1].set_xlabel('Count')
ax[1].set_ylabel('Ingredient')
plt.tight_layout()
plt.savefig('C:/Users/SAHANA/PycharmProjects/DataWrangling/Static/most_common_ingredients.png')


"""Average Nutritional Values per Recipe (scaled down):
**bold text**
For the purpose of visualization, this plot displays the average nutritional values for sodium, fat, calories, and protein per recipe. It is evident that the averages for calories and sodium are very high, indicating that a lot of recipes are heavy in both energy and salt. Note: Because the values have been scaled down for comparative presentation, the actual average values are shown as text above each bar for clarity.

**Average Recipe Rating: **

The average rating plot displays the average rating, or around 3.71 out of 5, for all recipes in the dataset. This shows that the recipes are well-received overall, indicating that consumers think they are high-quality recipes.
"""

# Plotting nutritional averages and average rating

# Data for nutritional averages plot
nutritional_labels = list(average_nutritional_info.keys())
nutritional_values = list(average_nutritional_info.values())

# Adjusting values for better visualization (scaling down)
scaled_nutritional_values = [value / 100 for value in nutritional_values]  # Scale down for better comparison

# Plot
fig, axs = plt.subplots(2, 1, figsize=(8, 10))

# Nutritional Averages Plot
axs[0].bar(nutritional_labels, scaled_nutritional_values, color='orange')
axs[0].set_title('Average Nutritional Values per Recipe (scaled down)')
axs[0].set_ylabel('Average Value (scaled down)')
for i, v in enumerate(scaled_nutritional_values):
    axs[0].text(i, v + 0.5, f"{nutritional_values[i]:.2f}", ha='center')

# Average Rating Plot
axs[1].bar('Average Rating', average_rating, color='teal')
axs[1].set_title('Average Rating of Recipes')
axs[1].set_ylim(0, 5)
axs[1].text(0, average_rating + 0.1, f"{average_rating:.2f}", ha='center')

plt.tight_layout()
plt.savefig('C:/Users/SAHANA/PycharmProjects/DataWrangling/Static/Average_Nutrition_Values_per_Recipe.png')
"""**Distribution of Most Common Categories:**

The dataset's emphasis on popular themes and nutritional considerations is evident from the pie chart, which shows the percentage of recipes that fall into the most common categories.

Distribution of Recipe Ratings:
**bold text**
 With bins divided into intervals of 0.5, the histogram shows the frequency of recipes at various rating levels. The distribution pattern of ratings is displayed in this plot, which highlights the dataset's overall propensity toward higher ratings among the recipes.
"""

# For the pie chart, we use the previously defined most_common_categories
categories_labels = [cat[0] for cat in most_common_categories]
categories_sizes = [cat[1] for cat in most_common_categories]
colors_pie = plt.cm.Paired(np.arange(len(categories_labels)))

# For the histogram, we use the previously collected ratings data
ratings = [recipe.get('rating', 0) for recipe in recipes_data if recipe.get('rating') is not None]

# Creating the plots
fig, axs = plt.subplots(1, 2, figsize=(14, 7))

# Pie chart for most common categories
axs[0].pie(categories_sizes, labels=categories_labels, autopct='%1.1f%%', startangle=140, colors=colors_pie)
axs[0].set_title('Distribution of Most Common Categories')

# Histogram for the distribution of recipe ratings
axs[1].hist(ratings, bins=np.arange(0, 5.5, 0.5), color='lightblue', edgecolor='black')
axs[1].set_title('Distribution of Recipe Ratings')
axs[1].set_xlabel('Rating')
axs[1].set_ylabel('Frequency')
axs[1].set_xticks(np.arange(0, 5.5, 0.5))

plt.tight_layout()
plt.savefig('C:/Users/SAHANA/PycharmProjects/DataWrangling/Static/Distribution_of_Recipe_Ratings.png')

"""In this study, we looked at a number of recipes to gather useful data regarding their nutritional worth, popularity, and ingredient makeup. The dataset contained all of the information about each dish, including the title, ingredients, nutritional information, categories, and user ratings.

##Findings:

Average Rating: With an average rating of roughly 3.71 out of 5, users have generally left positive reviews for the recipes.

###Nutritional Information:

The typical recipe contains 346g of fat, which is a notably high amount.
A recipe's average caloric content is approximately 6308, suggesting that many of the recipes are heavy in energy.

For each recipe, the average amounts of protein and salt are about 100g and 6212 mg, respectively. These are significant amounts that may not match the daily dietary guidelines.

###Top-Rated Groups:

The ubiquity of labels such as "Vegetarian," "Peanut Free," "Soy Free," "Bon Appétit," and "Tree Nut Free" highlights the significance of dietary choices and restrictions.

Most Frequently Used Ingredients: It's clear that basic ingredients like olive oil and salt


##Recommendations:

###1. Improve Variety in Diet:

Given to the popularity of recipes that meet particular dietary requirements (such as "Peanut Free" or "Soy Free"), it is a good idea to expand the variety of recipes in the collection to accommodate a wider range of dietary preferences and constraints. This strategy may aid in drawing in and keeping a larger audience.

###2. Encourage Healthier Alternatives:

It is advised to introduce dishes with healthier nutritional profiles in light of the high average values for fat, calories, and sodium. This might entail highlighting recipes that are lower in sodium and calories and offering advice on how to alter already-existing recipes to make them healthier.

###3.Expand The Use of Ingredients:

To combat the overabundance of staples like salt and olive oil, promoting the use of a wider range of seasonings, herbs, and nutritious oils could improve dish flavor profiles and provide health advantages.

###4.Educational Efforts:

It appears from the data that there may not be enough emphasis or knowledge about dietary balance. The project might benefit greatly from the creation of educational content that informs viewers about the value of varied components, nutritional wellness, and how to alter recipes for better health.


###5.User Involvement:

Using comments and ratings from users can help inform the creation of new recipes and the modification of current ones. A more active and contented community can be created by emphasizing recipes that have received good ratings or by enhancing recipes based on user ideas.






By guiding the project in line with these findings and recommendations, we may raise the standard and diversity of the recipe library, satisfy a larger range of dietary needs and preferences, and motivate people to adopt good eating habits. By putting these recommendations into effect, you'll ensure that the project proceeds rationally and successfully, relying on obtained data and user input, in addition to achieving the goal of providing insightful material resulting from data analysis.
"""